cvt_dailyPlanner/Controllers/CreateTaskController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using cvt_dailyPlanner.Data.Interface.IRepository;
using cvt_dailyPlanner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cvt_dailyPlanner.Controllers
{
    public class CreateTaskController : Controller
    {
        public readonly IRepository _repository;
        private readonly ILogger<CreateTaskController> _logger;
        public CreateTaskController(IRepository repository, ILogger<CreateTaskController> logger)
        {
            _repository = repository;
            _logger = logger;
        }
        // GET: /<controller>/
        public IActionResult Index(string date)
        {
            ViewBag.date = date;
            return View();
        }

        public IActionResult Create (DailyTaskViewModel dtv, string StartDate, string EndDate)
        {
            _logger.LogInformation("Начали создавть задачу");
            try
            {
                CultureInfo culture = new CultureInfo("ru-RU");
                dtv.StartDate = DateTime.Parse(StartDate, culture);
                if (!string.IsNullOrEmpty(EndDate))
                    dtv.EndDate = DateTime.Parse(EndDate, culture);

                _repository.CreateTask(dtv);
                
            }
            catch (Exception ex)
            {
                _logger.LogError("Ошибка создания задачи", ex);
            }
            _logger.LogInformation("Задача созданна");
            return RedirectToRoute(new { controller = "Planner", action="Index"});
        }
    }
}

cvt_dailyPlanner/Views/CreateTask/Index.cshtml
@model DailyTaskViewModel

<div>
    <div class="container">
        <form method="post" asp-controller="CreateTask" asp-action="Create">
            <div class="my-3 p-3 bg-white rounded shadow-sm">
                <div class="mb-3">
                    <label>Тема</label>
                    <input type="text" asp-for="Sub" class="form-control" id="firstName" placeholder="" value="" required="">

                    <div class="invalid-feedback">
                        Valid first name is required.
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 mb-3">
                        <label>Тип задачи</label>
                        <label for="RType"></label>
                        <select asp-for="TaskType"
                                class="custom-select d-block w-100" id="country" required="" onchange="Selected(this)">
                            <option>Встреча</option>
                            <option>Дело</option>
                            <option>Памятка</option>
                        </select>
                    </div>
                    <div class="col-md-4 mb-3" id="StartDate">
                        <label>Дата начала</label>
                        <input name="StartDate" value="@ViewBag.date" type="text"
                               class="form-control single-data-time-picker" id="date" placeholder="Дата" required>
                    </div>
                    <div class="col-md-4 mb-3" id="EndDate">
                        <label>Дата завершения</label>
                        <!-- <input type="date" class="form-control date-picker" id="date" name="date" placeholder="Дата" required> -->
                        <input name="EndDate" type="text" class="form-control single-data-time-picker" id="startDate" value="">
                    </div>
                </div>

                <div class="row" id="Place">
                    <div class="col-md-8">
                        <label>Место встречи</label>
                        <input asp-for="Place" type="text" class="form-control"
                               id="firstName" placeholder="" value="">
                    </div>
                </div>

                <div class="row flex-nowrap justify-content-end pr-3">
                    <a class="btn btn-danger" href="javascript:history.go(-1)">Отмена</a>
                    <input class="btn btn-success ml-2" type="submit" value="Создать" />
                </div>
            </div>
        </form>



    </div>
</div>