cvt_dailyPlanner/Controllers/PlannerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using cvt_dailyPlanner.Data.Interface;
using cvt_dailyPlanner.Data.Interface.IRepository;
using cvt_dailyPlanner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cvt_dailyPlanner.Controllers
{
    public class PlannerController : Controller
    {

        public readonly IRepository _repository;
        private readonly ILogger<HomeController> _logger;

        public PlannerController(IRepository repository, ILogger<HomeController> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        // GET: /<controller>/
        public IActionResult Index(DailyTasksViewModel dtv)
        {
            DailyTasksViewModel obj = dtv ?? new DailyTasksViewModel();
            var tasks = _repository.GetAllDailyPlan;
            obj.dailyTasks = tasks.OrderBy(t => t.StartDate);
            //ViewDate["period"] = "Index";
            return View(obj);
        }

        public IActionResult Week()
        {
            DailyTasksViewModel obj = new DailyTasksViewModel();
            obj.dailyTasks = _repository.WeekTask.GetActualyWeekPlan;
            //ViewBag["period"] = "Week";
            return View(obj);
        }

        public IActionResult Find(string Sub)
        {
            DailyTasksViewModel obj = new DailyTasksViewModel();
            try
            {
                var tasks = _repository.GetAllDailyPlan;
                obj.dailyTasks = tasks.Where(t=> t.Sub.Contains(Sub));
            }
            catch(Exception ex)
            {
                obj.dailyTasks = null;
                _logger.LogError("Не получилось найти задание", ex);
            }

            return View("Index", obj);
        }

        public IActionResult Month(bool isAllTask)
        {
            DailyTasksViewModel obj = new DailyTasksViewModel();
            var tasks = _repository.MonthTask.GetActualyMonthPlan;
            obj.dailyTasks = tasks.OrderBy(t=> t.StartDate);
            if (isAllTask)
            {
                DateTime today = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                obj.filter = new FilterViewModel();
                obj.filter.SelectDate = string.Format("{0} - {1}",
                    today.ToString("dd.MM.yyyy"),
                    today.AddMonths(1).ToString("dd.MM.yyyy"));
                obj.filter.DateTypeFilter = true;
                obj.filter.selectDateFilter = true;
                return View("Index", obj);
            }
            else
            {
                return View(obj);
            }
            
        }


        public IActionResult Day(string todayDay)
        {
            CultureInfo culture = new CultureInfo("ru-RU");

            DailyTasksViewModel obj = new DailyTasksViewModel();
            if(!string.IsNullOrEmpty(todayDay))
            {
                DateTime date = DateTime.Parse(todayDay, culture);
                obj.dailyTasks = _repository.DailyTask.GetDailyPlanByDay(date);
            }
                
            else
                obj.dailyTasks = _repository.DailyTask.GetTodayPlan;

            ViewBag.period = "Day";
            ViewBag.date = todayDay ?? DateTime.Now.ToString("dd.MM.yyyy");
            return View(obj);
        }

        public IActionResult Task(int id)
        {
            IDailyTask obj = _repository.getTaskById(id);
            return View(obj);
        }

        public IActionResult Update(DailyTaskViewModel dtv, string period)
        {
            _logger.LogInformation("Начали создавть задачу");
            try
            {
                _repository.UpdateTask(dtv);
            }
            catch (Exception ex)
            {
                _logger.LogError("Ошибка создания задачи", ex);
            }
            _logger.LogInformation("Задача созданна");
            return View("Task", dtv);
        }

        public IActionResult Filter(DailyTasksViewModel dtv)
        {
            var task = _repository.GetAllDailyPlan;

            if (!string.IsNullOrEmpty(dtv.filter.TaskType))
                task = task.Where(t=> t.TaskType == dtv.filter.TaskType);

            if (dtv.filter.DateType == "down")
                task = task.OrderByDescending(t => t.StartDate);
            else
                task = task.OrderBy(t => t.StartDate);

            if (!string.IsNullOrEmpty(dtv.filter.SelectDate))
            {
                var selectDates = dtv.filter.SelectDate.Split('-');
                CultureInfo culture = new CultureInfo("ru-RU");
                DateTime startDate = DateTime.Parse(selectDates[0], culture);
                DateTime endDate = DateTime.Parse(selectDates[1], culture);
                task = task.Where(t => t.StartDate >= startDate && t.StartDate <= endDate).ToList();
            }

            dtv.dailyTasks = task;
            return View("Index", dtv);
        }

        [HttpPost]
        public bool Done(int id)
        {
            DailyTaskViewModel dtv = _repository.getTaskById(id);
            _logger.LogInformation("Выполняем задачу");
            try
            {
                dtv.IsDone = !dtv.IsDone;
                _repository.UpdateTask(dtv);
            }
            catch(Exception ex)
            {
                _logger.LogDebug("Не удалось выполнить задачу", ex);
                dtv.IsDone = !dtv.IsDone;
                return false;
            }
            
            _logger.LogInformation("Выполнили задачу");
            return true;
        }
    }
}

cvt_dailyPlanner/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cvt_dailyPlanner.Controllers
{
    public class TaskController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

cvt_dailyPlanner/Views/Planner/Day.cshtml
@model DailyTasksViewModel

    <div class="my-3 p-3 bg-white rounded shadow-sm">

        @{
            string date = ViewBag.date;
            foreach (var el in Model.dailyTasks)
            {
                @Html.Partial("TaskTemplate", new ViewDataDictionary(ViewData) {
                   { "task", el} })
            }
        }

        @Html.Partial("CreateTaskTemplate", date)

    </div>

cvt_dailyPlanner/Views/Planner/Index.cshtml
@model DailyTasksViewModel

@{
    ViewData["Model"] = Model;
    string jsonModel = Json.Serialize(Model).ToString();
    <div class="row justify-content-end" style="cursor:pointer" onclick="VisibleFilter(@jsonModel)">
        <div class="btn btn-primary mt-3 mr-3 col-2">Фильтр</div>
    </div>
}
@Html.Partial("FilterTemplate", Model)
<div class="my-3 p-3 bg-white rounded shadow-sm">
    @{
        DailyTaskViewModel lastTask = null;
        foreach (var el in Model.dailyTasks)
        {
            if (lastTask == null || el.StartDate.ToShortDateString() != lastTask.StartDate.ToShortDateString())
            {
                <div class="border-bottom border-gray pb-2 mb-0 mt-3">
                    @el.StartDate.ToString("dd.MM.yyyy")
                </div>
            }

            lastTask = el;

            @Html.Partial("TaskTemplate", new ViewDataDictionary(ViewData)
    { { "task", el} });
        }
    }
</div>

cvt_dailyPlanner/Views/Planner/Month.cshtml


<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="row border-bottom border-gray text-center">
        <div class="col border-right border-gray">
            Пн
        </div>
        <div class="col border-right border-gray">
            Вт
        </div>
        <div class="col border-right border-gray">
            Ср
        </div>
        <div class="col border-right border-gray">
            Чт
        </div>
        <div class="col border-right border-gray">
            Пт
        </div>
        <div class="col border-right border-gray">
            Сб
        </div>
        <div class="col border-right border-gray">
            Вс
        </div>
    </div>
    @{
        var month = DateTime.Now.Month;
        var year = DateTime.Now.Year;
        var daysInMonth = DateTime.DaysInMonth(year, month);
        var daysInLastMonth = DateTime.DaysInMonth(year, month - 1);
        var nextDays = 1;
        int date = 1;
        for (var i = 0; i < 5; i++)
        {
            <div class="row mt-2 border-bottom border-gray pb-2" style="height: 90px;">

                @{
                    for (int d = 1; d < 8; d++)
                    {
                        var today = new DateTime(year, month, date);
                        var weekDay = (int)today.DayOfWeek;

                        if (weekDay == d ||
                           (d == 7 && weekDay == 0))
                        {
                            @Html.ActionLink(today.Day.ToString(), "Day", "Planner",
                                               new { period = "Day", todayDay = today.ToString("dd.MM.yyyy") },
                                               new { @class = "col border-right border-gray" })



                            if (date != daysInMonth)
                            {
                                ++date;
                            }

                        }
                        else
                        {
                            if (i == 0)
                            {
                                var lastDay = daysInLastMonth - 5 + d;
                                <div class="col border-right border-gray" style="color: #e5e5e5">@lastDay</div>
                            }
                            else
                            {
                                <div class="col border-right border-gray" style="color: #e5e5e5">@nextDays</div>
                                nextDays += 1;
                            }

                        }
                    }
                }

            </div>
        }
    }

</div>

@Html.ActionLink("Все задачи", "Month", "Planner", new { isAllTask = true })

cvt_dailyPlanner/Views/Planner/MonthTasks.cshtml
@model DailyTasksViewModel

@{
    ViewData["Model"] = Model;
    string jsonModel = Json.Serialize(Model).ToString();
    <div class="row justify-content-end" style="cursor:pointer" onclick="VisibleFilter(@jsonModel)">
        <div class="btn btn-primary mt-3 mr-3 col-2">Фильтр</div>
    </div>
}
@Html.Partial("FilterTemplate", Model)
<div class="my-3 p-3 bg-white rounded shadow-sm">
    @{
        DailyTaskViewModel lastTask = null;
        foreach (var el in Model.dailyTasks)
        {
            if (lastTask == null || el.StartDate.ToShortDateString() != lastTask.StartDate.ToShortDateString())
            {
                <div class="border-bottom border-gray pb-2 mb-0 mt-3">
                    @el.StartDate.ToString("dd.MM.yyyy")
                </div>
            }

            lastTask = el;

            @Html.Partial("TaskTemplate", new ViewDataDictionary(ViewData)
{ { "task", el} });
        }
    }
</div>

cvt_dailyPlanner/Views/Planner/Task.cshtml
@model DailyTaskViewModel

<div class="container">
    <form method="post" asp-controller="Planner" asp-action="Update">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <div class="mb-3">
                <label>Тема</label>
                <input type="text" name="Sub" class="form-control" id="firstName" placeholder="" value="@Model.Sub" required="" disabled>

                <div class="invalid-feedback">
                    Valid first name is required.
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-3">
                    <label>Тип задачи</label>
                    <label for="RType"></label>
                    <select asp-for="TaskType"
                            class="custom-select d-block w-100" id="taskType" required="" onchange="Selected(this)" disabled>
                        <option value="@Model.TaskType">@Model.TaskType</option>
                    </select>
                </div>
                <div class="col-md-4 mb-3" id="StartDate">
                    <label>Дата начала</label>
                    <input name="startDate" value="@Model.StartDate.ToString("dd.MM.yyyy")" type="text"
                           class="form-control single-data-time-picker" id="date" placeholder="Дата" required disabled>
                </div>
                @{
                    if (Model.TaskType != "Памятка")
                    {
                        <div class="col-md-4 mb-3" id="EndDate">
                            <label>Дата завершения</label>
                            <!-- <input type="date" class="form-control date-picker" id="date" name="date" placeholder="Дата" required> -->
                            <input name="endDate" type="text" class="form-control single-data-time-picker"
                                   id="startDate" value="@Model.EndDate.Value.ToString("dd.MM.yyyy")" disabled>
                        </div>
                    }
                }

            </div>

            @{
                if (Model.TaskType == "Встреча")
                {
                    <div class="row" id="Place">
                        <div class="col-md-8">
                            <label>Место встречи</label>
                            <input name="place" type="text" class="form-control"
                                   id="firstName" placeholder="" value="@Model.Place" disabled>
                        </div>
                    </div>
                }

            }


            <div class="row flex-nowrap justify-content-end pr-3">
                <a class="btn btn-success" href="javascript:history.go(-1)">Ок</a>
            </div>
        </div>
    </form>



</div>

cvt_dailyPlanner/Views/Planner/Week.cshtml
@model DailyTasksViewModel
@{
    var weekDay = (int)DateTime.Now.DayOfWeek;
    weekDay = weekDay == 0 ? 7 : weekDay;
    for (int i = 1; i < 8; i++)
    {

        var date = DateTime.Now.AddDays(i - weekDay);

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">@date.ToString("dd.MM.yyyy")</h6>
        @{
            foreach (var el in Model.dailyTasks.Where(t =>
                (int)t.StartDate.DayOfWeek == i ||
                    ((int)t.StartDate.DayOfWeek == 0 && i == 7)))
            {
                @Html.Partial("TaskTemplate", new ViewDataDictionary(ViewData) {
                   { "task", el}})
            }
        }
        @Html.Partial("CreateTaskTemplate", date.ToString("dd.MM.yyyy"))
        @Html.ActionLink("Все задачи", "Day", "Planner", new { todayDay = date.ToString("dd.MM.yyyy") })
    </div>
    }
}